In [1]:
#speed

a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []

import time 

start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])

print(time.time()-start)

0.6109411716461182


In [2]:
import numpy as np

a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start)

0.0522310733795166


In [3]:
#Memory

a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [4]:
a = np.arange(10000000,dtype=np.int64)
sys.getsizeof(a)

80000112

In [5]:
# Advance indexing 

#Fancy indexing 

a = np.arange(24).reshape(6,4)
a[:,[0,2,1]]

array([[ 0,  2,  1],
       [ 4,  6,  5],
       [ 8, 10,  9],
       [12, 14, 13],
       [16, 18, 17],
       [20, 22, 21]])

In [6]:
#Boolean Indexing 

import numpy as np

a = np.random.randint(1,100,24).reshape(6,4)
a

array([[78, 42, 87, 21],
       [23, 59, 68, 77],
       [32, 83, 33, 64],
       [30, 36, 50, 57],
       [46, 49, 77, 81],
       [82, 59, 36, 91]])

In [7]:
#find all the numbers which is greater than 50
a[a>50]

#can be used to filter 

array([78, 87, 59, 68, 77, 83, 64, 57, 77, 81, 82, 59, 91])

In [8]:
#find even numbers 

a % 2 == 0
a[a % 2 == 0]

array([78, 42, 68, 32, 64, 30, 36, 50, 46, 82, 36])

In [9]:
#fint the numbers which are greater than 50 and even 
a[( a > 50)&( a % 2 == 0)]


array([78, 68, 64, 82])

In [10]:
#Find the number which is not divisible by 7

a[~(a % 7 == 0)]

array([78, 87, 23, 59, 68, 32, 83, 33, 64, 30, 36, 50, 57, 46, 81, 82, 59,
       36])

In [11]:
#Broadcasting super important

a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print(a + b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


In [12]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)
print(a)
print(b)
print("----------result------------")
print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
----------result------------
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [13]:
a = np.arange(12).reshape(3,4) #here the broadcasting will not run
b = np.arange(3)
print(a)
print(b)
print("----------result------------")
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]
----------result------------


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [ ]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a+b)



[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
import numpy as np
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)
print(a)
print(b)
b
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

In [ ]:
#Working with Mathematical formulas

a = np.arange(12)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021])

In [ ]:
#Sigmoid function

def sigmoid(array):
    return 1/(1+np.exp(-(array)))

a = np.arange(100)

sigmoid(a)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661,
       0.9999546 , 0.9999833 , 0.99999386, 0.99999774, 0.99999917,
       0.99999969, 0.99999989, 0.99999996, 0.99999998, 0.99999999,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.     

In [ ]:
# Mean Square error

actual = np.random.randint(1,100,40)
predicted = np.random.randint(1,100,40)

In [ ]:
actual

array([54, 49, 30,  5, 33, 65, 54, 30, 45, 28,  1, 30, 78, 32, 79, 40, 21,
       82, 82, 36, 41, 10, 34,  8, 78, 82, 80, 39, 64, 11, 65, 80, 71, 61,
        7, 32, 87, 36, 89, 20])

In [ ]:
predicted

array([19, 63,  7, 76, 52, 94, 76, 92, 94, 84, 15, 34, 51, 39, 42, 64, 36,
       34, 98, 55, 21, 56, 97, 13, 42, 85, 58, 59, 63, 42, 93, 16, 30, 38,
       31, 50, 93, 36, 69, 57])

In [ ]:
def mes(actual,predicted):
    return np.mean((actual-predicted)**2).item()

mes(actual,predicted)



1089.875

In [ ]:
#Working with missing value np.nan

a = np.array([1,2,3,4,np.nan,6])
a

array([ 1.,  2.,  3.,  4., nan,  6.])

In [ ]:
a[~np.isnan(a)]

array([1., 2., 3., 4., 6.])

In [ ]:
#np.sort

a = np.random.randint(50,500,26)
a

array([263, 241, 165, 352, 477, 264, 486, 359,  76, 209, 409, 157, 115,
       215,  86,  83, 108, 299, 338, 242, 401, 498, 248, 268, 140, 410])

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[39, 61, 94, 89],
       [54, 86, 64, 94],
       [39, 63, 47, 22],
       [71, 38, 66, 37],
       [93,  7, 79, 16],
       [88, 50, 78, 89]])

In [ ]:
np.sort(a)

array([ 76,  83,  86, 108, 115, 140, 157, 165, 209, 215, 241, 242, 248,
       263, 264, 268, 299, 338, 352, 359, 401, 409, 410, 477, 486, 498])

In [ ]:
np.sort(b,axis=1)

array([[39, 61, 89, 94],
       [54, 64, 86, 94],
       [22, 39, 47, 63],
       [37, 38, 66, 71],
       [ 7, 16, 79, 93],
       [50, 78, 88, 89]])

In [ ]:
np.append(a,37)

array([263, 241, 165, 352, 477, 264, 486, 359,  76, 209, 409, 157, 115,
       215,  86,  83, 108, 299, 338, 242, 401, 498, 248, 268, 140, 410,
        37])

In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[39., 61., 94., 89.,  1.],
       [54., 86., 64., 94.,  1.],
       [39., 63., 47., 22.,  1.],
       [71., 38., 66., 37.,  1.],
       [93.,  7., 79., 16.,  1.],
       [88., 50., 78., 89.,  1.]])

In [ ]:
#np.concatinate

c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [ ]:
#np.unique

e = np.array([1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8])
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#np.expand_dims

np.expand_dims(a,axis=0)

array([[263, 241, 165, 352, 477, 264, 486, 359,  76, 209, 409, 157, 115,
        215,  86,  83, 108, 299, 338, 242, 401, 498, 248, 268, 140, 410]])

In [ ]:
a.shape

(26,)

In [ ]:
#np.expand_dims

np.expand_dims(a,axis=1)

array([[263],
       [241],
       [165],
       [352],
       [477],
       [264],
       [486],
       [359],
       [ 76],
       [209],
       [409],
       [157],
       [115],
       [215],
       [ 86],
       [ 83],
       [108],
       [299],
       [338],
       [242],
       [401],
       [498],
       [248],
       [268],
       [140],
       [410]])

In [ ]:
#np.where 
np.where(a>250)

(array([ 0,  3,  4,  5,  6,  7, 10, 17, 18, 20, 21, 23, 25]),)

In [ ]:
np.where(a>250,0,a)

array([  0, 241, 165,   0,   0,   0,   0,   0,  76, 209,   0, 157, 115,
       215,  86,  83, 108,   0,   0, 242,   0,   0, 248,   0, 140,   0])

In [ ]:
np.where(a%2==0,1,a)

array([263, 241, 165,   1, 477,   1,   1, 359,   1, 209, 409, 157, 115,
       215,   1,  83,   1, 299,   1,   1, 401,   1,   1,   1,   1,   1])

In [ ]:
#np.argmax

a

array([263, 241, 165, 352, 477, 264, 486, 359,  76, 209, 409, 157, 115,
       215,  86,  83, 108, 299, 338, 242, 401, 498, 248, 268, 140, 410])

In [ ]:
np.argmax(a)

np.int64(21)

In [ ]:
b

array([[39, 61, 94, 89],
       [54, 86, 64, 94],
       [39, 63, 47, 22],
       [71, 38, 66, 37],
       [93,  7, 79, 16],
       [88, 50, 78, 89]])

In [ ]:
np.argmax(b,axis=0)

array([4, 1, 0, 1])

In [ ]:
np.argmax(b,axis=1)

array([2, 3, 1, 0, 0, 3])

In [ ]:
a


array([263, 241, 165, 352, 477, 264, 486, 359,  76, 209, 409, 157, 115,
       215,  86,  83, 108, 299, 338, 242, 401, 498, 248, 268, 140, 410])

In [ ]:
np.cumsum(a)

array([ 263,  504,  669, 1021, 1498, 1762, 2248, 2607, 2683, 2892, 3301,
       3458, 3573, 3788, 3874, 3957, 4065, 4364, 4702, 4944, 5345, 5843,
       6091, 6359, 6499, 6909])

In [ ]:
np.cumsum(b,axis=0)

array([[ 39,  61,  94,  89],
       [ 93, 147, 158, 183],
       [132, 210, 205, 205],
       [203, 248, 271, 242],
       [296, 255, 350, 258],
       [384, 305, 428, 347]])

In [ ]:
np.cumprod(a)

array([                 263,                63383,             10458195,
                 3681284640,        1755972773280,      463576812145920,
         225298330702917120,  7095124427509039616,  4273878353110013952,
        7796860261934438400, -2370877620567123968, -3292904954847430656,
        8697555740446058496,  6853332751237863424,  -909193752249397248,
       -1676105141861765120,  3448085416024883200, -2040128736294813696,
       -7033982140393619456, -5123223193977159680, -6823908603080802304,
       -4105574771682050048, -3611619323123073024, -8683286764086886400,
        1824961892666310656, -8082131028904247296])

In [ ]:
np.percentile(a,50).item()

255.5

In [ ]:
np.histogram(a,bins=[0,100,200,300,400,500]) #show the frequency 

(array([3, 5, 9, 3, 6]), array([  0, 100, 200, 300, 400, 500]))

In [ ]:
#np.corrcoef

salary = np.array([20000,30000,35000,40000,50000])
experience = np.array([1,2,3,4,5,])
np.corrcoef(salary,experience)

array([[1.        , 0.98994949],
       [0.98994949, 1.        ]])

In [ ]:
#np.isin
items = np.random.randint(1,500,24)

a[np.isin(a,items)]

array([165, 157, 108, 498, 410])

In [ ]:
#np.flip

np.flip(a)


array([410, 140, 268, 248, 498, 401, 242, 338, 299, 108,  83,  86, 215,
       115, 157, 409, 209,  76, 359, 486, 264, 477, 352, 165, 241, 263])

In [ ]:
np.flip(b,axis=0)

array([[88, 50, 78, 89],
       [93,  7, 79, 16],
       [71, 38, 66, 37],
       [39, 63, 47, 22],
       [54, 86, 64, 94],
       [39, 61, 94, 89]])

In [ ]:
b

array([[39, 61, 94, 89],
       [54, 86, 64, 94],
       [39, 63, 47, 22],
       [71, 38, 66, 37],
       [93,  7, 79, 16],
       [88, 50, 78, 89]])

In [ ]:
#np.put 
a

array([263, 241, 165, 352, 477, 264, 486, 359,  76, 209, 409, 157, 115,
       215,  86,  83, 108, 299, 338, 242, 401, 498, 248, 268, 140, 410])

In [ ]:
np.put(a,[0,4],[467,124])
a

array([467, 241, 165, 352, 124, 264, 486, 359,  76, 209, 409, 157, 115,
       215,  86,  83, 108, 299, 338, 242, 401, 498, 248, 268, 140, 410])

In [ ]:
np.delete(a,[0,8,5,2])

array([241, 352, 124, 486, 359, 209, 409, 157, 115, 215,  86,  83, 108,
       299, 338, 242, 401, 498, 248, 268, 140, 410])

In [ ]:
#set functions 

m = np.random.randint(0,40,12)
n = np.random.randint(0,40,12)

np.union1d(m,n)

array([ 2,  3,  9, 12, 13, 14, 19, 21, 24, 26, 27, 30, 33, 34, 36, 37, 38])

In [ ]:
np.intersect1d(m,n)

array([19, 36])

In [ ]:
np.setdiff1d(m,n)

array([ 9, 13, 14, 24, 26, 27, 37, 38])

In [ ]:
np.setxor1d(m,n)

array([ 2,  3,  9, 12, 13, 14, 21, 24, 26, 27, 30, 33, 34, 37, 38])

In [ ]:
np.clip(a,min=247)

array([467, 247, 247, 352, 247, 264, 486, 359, 247, 247, 409, 247, 247,
       247, 247, 247, 247, 299, 338, 247, 401, 498, 248, 268, 247, 410])